#!/bin/sh

echo ""
echo ""
echo "  _   _   _   _   _  "
echo " / \ / \ / \ / \ / \ "
echo "( C | A | B | B | Y |"
echo " \_/ \_/ \_/ \_/ \_/ "
echo ""
echo ""
echo "┏ Cabby Git Control ------------"
echo ""
echo ""
read -p "   Please Enter Your Commit Message: " msg
echo ""
echo ""
echo "┗ --------------------------------"
echo ""
echo ""
echo "┏ Cabby Main Repo --------------"
echo ""
echo ""
echo "   Adding Files to git"
git add .
echo ""
echo "   Commiting Files"
echo ""
git commit -m "$msg"
echo ""
echo "   Pushing Files to Bitbucket"
git push bb master
echo ""
echo "   Pushing Files to Github"
git push github master
echo ""
echo ""
echo "--------------------------------"
echo ""
echo ""
echo "   All Process are Done!"
echo ""
echo ""
echo "┗ --------------------------------"
