#!/bin/sh

STATIC_DIR="static"

echo ""
echo ""
echo "  /$$$$$$   /$$$$$$  /$$$$$$$  /$$$$$$$  /$$     /$$"
echo " /$$__  $$ /$$__  $$| $$__  $$| $$__  $$|  $$   /$$/"
echo "| $$  \__/| $$  \ $$| $$  \ $$| $$  \ $$ \  $$ /$$/ "
echo "| $$      | $$$$$$$$| $$$$$$$ | $$$$$$$   \  $$$$/  "
echo "| $$      | $$__  $$| $$__  $$| $$__  $$   \  $$/   "
echo "| $$    $$| $$  | $$| $$  \ $$| $$  \ $$    | $$    "
echo "|  $$$$$$/| $$  | $$| $$$$$$$/| $$$$$$$/    | $$    "
echo "\______/ |__/  |__/|_______/ |_______/     |__/    "
echo ""
echo ""
echo "â” Cabby Git Control ------------"
echo ""
echo ""
read -p "   Please Enter Your Commit Message: " msg
echo ""
echo ""
echo "â”— --------------------------------"
echo ""
echo ""
echo "â” Cabby Main Repo --------------"
echo ""
echo ""
echo "   Adding Files to git"
git add .
echo ""
echo "   Commiting Files"
echo ""
git commit -m "$msg"
echo ""
echo "   Pushing Files to Bitbucket"
git push bb master
echo ""
echo "   Pushing Files to Github"
git push github master
echo ""
echo ""
echo "â”— --------------------------------"
echo ""
echo ""
echo "   All Process are Done!"
echo ""
echo ""
echo "â”— --------------------------------"
